### ISSUE TITLE
[L5.3.x] BadMethodCallException: Method controller does not exist

### ISSUE THREAD

**Issue by rjsworking** [barryvdh/laravel-translation-manager#125]
Hi. Tried to add this package to a laravel 5.3.x app and got the following error while publishing config/migrations: 

``` php
  [BadMethodCallException]
  Method controller does not exist.
```

laravel.log trace

``` php
#0 C:\Work\www\projects\locales2\vendor\barryvdh\laravel-translation-manager\src\ManagerServiceProvider.php(89): Illuminate\Routing\Router->__call('controller', Array)
#1 [internal function]: Barryvdh\TranslationManager\ManagerServiceProvider->Barryvdh\TranslationManager\{closure}(Object(Illuminate\Routing\Router))
#2 C:\Work\www\projects\locales2\vendor\laravel\framework\src\Illuminate\Routing\Router.php(319): call_user_func(Object(Closure), Object(Illuminate\Routing\Router))
#3 C:\Work\www\projects\locales2\vendor\barryvdh\laravel-translation-manager\src\ManagerServiceProvider.php(90): Illuminate\Routing\Router->group(Array, Object(Closure))
#4 [internal function]: Barryvdh\TranslationManager\ManagerServiceProvider->boot(Object(Illuminate\Routing\Router))
#5 C:\Work\www\projects\locales2\vendor\laravel\framework\src\Illuminate\Container\Container.php(507): call_user_func_array(Array, Array)
#6 C:\Work\www\projects\locales2\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(759): Illuminate\Container\Container->call(Array)
#7 C:\Work\www\projects\locales2\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(742): Illuminate\Foundation\Application->bootProvider(Object(Barryvdh\TranslationManager\ManagerServiceProvider))
#8 [internal function]: Illuminate\Foundation\Application->Illuminate\Foundation\{closure}(Object(Barryvdh\TranslationManager\ManagerServiceProvider), 11)
#9 C:\Work\www\projects\locales2\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(743): array_walk(Array, Object(Closure))
#10 C:\Work\www\projects\locales2\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\BootProviders.php(17): Illuminate\Foundation\Application->boot()
#11 C:\Work\www\projects\locales2\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(203): Illuminate\Foundation\Bootstrap\BootProviders->bootstrap(Object(Illuminate\Foundation\Application))
#12 C:\Work\www\projects\locales2\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(246): Illuminate\Foundation\Application->bootstrapWith(Array)
#13 C:\Work\www\projects\locales2\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(108): Illuminate\Foundation\Console\Kernel->bootstrap()
#14 C:\Work\www\projects\locales2\artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 {main}  
```

Cheers

**Comment by filipveschool** [comment]
Change ->controller with Get or post or whatever is necessary. I changed with get and iT worked.

**Comment by rsdev000** [comment]
@filipveschool Thanks. It works as a quick fix but @barryvdh should fix the service provider.
Cheers

**Comment by barryvdh** [comment]
Yeah, please submit a PR

**Comment by rsdev000** [comment]
@barryvdh Will test as deep as I can. Just found another issue with query builder lists() method that was removed in L5.3

**Comment by jcorrego** [comment]
Subscribe

**Comment by duikb00t** [comment]
`$router->group($config, function($router)
        {
            $router->get('view/{group}', 'Controller@getView');
            $router->controller('/', 'Controller');
        });
`

When I apply the changes like @filipveschool  mentioned I am unable to install it successfully.

> Invalid route action: [Barryvdh\TranslationManager\Controller]

**Comment by uusa35** [comment]
pull request it pleaseeeeeee

**Comment by cfreak** [comment]
please accept pull request from uusa35

**Comment by dmitrijsmihailovs** [comment]
Still getting this error + error that lists method does not exist.

**Comment by Exoder** [comment]
Have same error (

**Comment by mbouclas** [comment]
:+1: Please accept uusa35's PR

**Comment by barryvdh** [comment]
Which one?

**Comment by mbouclas** [comment]
the one that fixes this error. It's on master, but when pulling it from composer as "barryvdh/laravel-translation-manager": "0.2.x" it produces this error (at least until early this week when i last tested it). If you pull "barryvdh/laravel-translation-manager": "dev-master", all is well

**Comment by barryvdh** [comment]
Oh you mean,  tag a new release? Can do that.

**Comment by mbouclas** [comment]
cheers

**Comment by barryvdh** [comment]
Tagged `v0.2.4`

**Comment by emilas44** [comment]
Does method lists() exist in L5.3??
i get this error when i want to use lists()

BadMethodCallException with message 'Method lists does not exist.'

**Comment by chhaihongsrun** [comment]
@emilas44 You saved my time.
Thanks
