### ISSUE TITLE
local.ERROR: Call to undefined function Barryvdh\TranslationManager\array_dot() in Laravel v6.0

### ISSUE THREAD

**Issue by saschati** [barryvdh/laravel-translation-manager#329]
Hi, I can’t understand why the package does not work, everything was done as indicated in Readme, error code:
```
local.ERROR: Call to undefined function Barryvdh\TranslationManager\array_dot() {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to undefined function Barryvdh\\TranslationManager\\array_dot() at /app/vendor/barryvdh/laravel-translation-manager/src/Manager.php:100)
[stacktrace]
#0 /app/vendor/barryvdh/laravel-translation-manager/src/Console/ImportCommand.php(40): Barryvdh\\TranslationManager\\Manager->importTranslations(false)
#1 [internal function]: Barryvdh\\TranslationManager\\Console\\ImportCommand->handle()
#2 /app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array(Array, Array)
#3 /app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#4 /app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#5 /app/vendor/laravel/framework/src/Illuminate/Container/Container.php(591): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#6 /app/vendor/laravel/framework/src/Illuminate/Console/Command.php(192): Illuminate\\Container\\Container->call(Array)
#7 /app/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#8 /app/vendor/laravel/framework/src/Illuminate/Console/Command.php(179): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#9 /app/vendor/symfony/console/Application.php(915): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#10 /app/vendor/symfony/console/Application.php(272): Symfony\\Component\\Console\\Application->doRunCommand(Object(Barryvdh\\TranslationManager\\Console\\ImportCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#11 /app/vendor/symfony/console/Application.php(148): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#12 /app/vendor/laravel/framework/src/Illuminate/Console/Application.php(90): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#13 /app/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(131): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#14 /app/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#15 {main}
"} 

   Symfony\Component\Debug\Exception\FatalThrowableError  : Call to undefined function Barryvdh\TranslationManager\array_dot()

  at /app/vendor/barryvdh/laravel-translation-manager/src/Manager.php:100
     96|                     $group        = "vendor/" . $vendorName;
     97|                 }
     98| 
     99|                 if ( $translations && is_array( $translations ) ) {
  > 100|                     foreach ( array_dot( $translations ) as $key => $value ) {
    101|                         $importedTranslation = $this->importTranslation( $key, $value, $locale, $group, $replace );
    102|                         $counter             += $importedTranslation ? 1 : 0;
    103|                     }
    104|                 }

```
I found a problem, the `array_dot()` function is not supported in Laravel 6.0, it was replaced by the static function class `Arr::dot()`. Сan you fix this?
**Manager.php line 100:**
```
if ( $translations && is_array( $translations ) ) {
       foreach ( array_dot( $translations ) as $key => $value ) {
               $importedTranslation = $this->importTranslation( $key, $value, $locale, $group, $replace );
               $counter             += $importedTranslation ? 1 : 0;
      }
}
```
to

```
if ( $translations && is_array( $translations ) ) {
      foreach (Illuminate\Support\Arr::dot( $translations ) as $key => $value ) {
             $importedTranslation = $this->importTranslation( $key, $value, $locale, $group, $replace );
             $counter             += $importedTranslation ? 1 : 0;
      }
}
```
Thanks in advance for your help:)

**Comment by barryvdh** [comment]
yeah please submit a PR

**Comment by voicecode-bv** [comment]
PR submitted: [https://github.com/barryvdh/laravel-translation-manager/pull/330](#330 )

**Comment by mixattack** [comment]
++
